kind: pipeline
name: default

steps:

  # Compile the code/run tests
- name: build
  image: hseeberger/scala-sbt:8u242_1.3.8_2.12.10
  commands:
  - sbt ci
  - echo Built $(cat version)
  environment:
    COURSIER_CACHE: .cache/coursier
  volumes:
    - name: sbt-cache
      path: /root/.sbt

  # Publish maven artifacts (on tag push)
- name: publish-to-artifactory
  image: hseeberger/scala-sbt:8u242_1.3.8_2.12.10
  commands:
  - echo Publishing version $(cat version)
  - sbt publish
  - echo done !
  environment:
    COURSIER_CACHE: .cache/coursier
    ART_USER:
      from_secret: username
    ART_PASSWORD:
      from_secret: password
  when:
    ref:
      - refs/tags/v*
  volumes:
  - name: sbt-cache
    path: /root/.sbt

volumes:
- name: sbt-cache
  temp: {}

---
kind: secret
name: username
data: epM48/FMMsOolVdGDs0z3oQeAMyPioOmshPfBRnmrtfNRag67Q==
---
kind: secret
name: password
data: krBDYD3HhDKTls34m7vad5oLDsk7PkLgmx3u10B3nCIpbYwWc+mq


