kind: pipeline
name: default

steps:

  # Compile the code/run tests
# - name: build
#   image: hseeberger/scala-sbt:8u242_1.3.8_2.12.10
#   commands:
#   - sbt ci
#   - echo Built $(cat version)
#   environment:
#     COURSIER_CACHE: .cache/coursier
#   volumes:
#     - name: sbt-cache
#       path: /root/.sbt

- name: build docker image
  image: docker
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker build -t weaver-scala-sbt-yarn:latest docker/

- name: build-site
  image: weaver-scala-sbt-yarn:latest
  pull: if-not-exists
  commands:
  - sbt 'docs/docusaurusCreateSite'
  environment:
    COURSIER_CACHE: .cache/coursier
  volumes:
    - name: sbt-cache
      path: /root/.sbt

  # Publish maven artifacts (on tag push)
- name: publish-to-artifactory
  image: hseeberger/scala-sbt:8u242_1.3.8_2.12.10
  commands:
  - echo Publishing version $(cat version)
  - sbt release
  - echo done !
  environment:
    COURSIER_CACHE: .cache/coursier
    ART_USER:
      from_secret: username
    ART_PASSWORD:
      from_secret: password
  when:
    ref:
      - refs/tags/v*
  volumes:
  - name: sbt-cache
    path: /root/.sbt

- name: publish-site
  image: weaver-scala-sbt-yarn:latest
  pull: if-not-exists
  commands:
  - mkdir -p $HOME/.ssh
  - ssh-keyscan -t rsa github.bamtech.co >> $HOME/.ssh/known_hosts
  - sbt 'docs/docusaurusPublishGhpages'
  environment:
    COURSIER_CACHE: .cache/coursier
    GIT_USER: $DRONE_COMMIT_AUTHOR
    GITHUB_DEPLOY_KEY:
      from_secret: github_deploy_public_key
  when:
    ref:
      - refs/tags/v*
  volumes:
    - name: sbt-cache
      path: /root/.sbt

volumes:
- name: sbt-cache
  temp: {}
- name: dockersock
  host:
    path: /var/run/docker.sock

---
kind: secret
name: username
data: epM48/FMMsOolVdGDs0z3oQeAMyPioOmshPfBRnmrtfNRag67Q==
---
kind: secret
name: password
data: krBDYD3HhDKTls34m7vad5oLDsk7PkLgmx3u10B3nCIpbYwWc+mq

